//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/MainInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainInputActions"",
    ""maps"": [
        {
            ""name"": ""Generic"",
            ""id"": ""43fa14f6-467f-4407-aab5-4ee79e31c65f"",
            ""actions"": [
                {
                    ""name"": ""GenericA"",
                    ""type"": ""Button"",
                    ""id"": ""e916b0ea-2867-4249-b158-65a92cfd3d76"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericB"",
                    ""type"": ""Button"",
                    ""id"": ""f2beeaa9-9b38-476c-b304-ac927e3782d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericY"",
                    ""type"": ""Button"",
                    ""id"": ""2ef2cb20-9d89-445e-b262-d3b0fa2f862b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericX"",
                    ""type"": ""Button"",
                    ""id"": ""9a88825b-560e-4c06-869b-a4c4baac432c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericLB"",
                    ""type"": ""Button"",
                    ""id"": ""706c0dea-e7cf-4862-bc72-0d84fa69e982"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericLT"",
                    ""type"": ""Button"",
                    ""id"": ""ea7baad3-ad33-4d44-b486-69e0aabec8e9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericRB"",
                    ""type"": ""Button"",
                    ""id"": ""a216e9c3-0edd-4715-83d6-5aa4bbb1b3f3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericRT"",
                    ""type"": ""Button"",
                    ""id"": ""b084d63d-8510-4b88-9d99-0b0e15099c9d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericL3"",
                    ""type"": ""Button"",
                    ""id"": ""a5419da6-157c-4b21-bc75-e0df9259fc1c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericR3"",
                    ""type"": ""Button"",
                    ""id"": ""b1dc6dad-00d4-42d4-8ffe-19ff640de721"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericSelect"",
                    ""type"": ""Button"",
                    ""id"": ""662eb34d-cfb2-4fbd-8842-b0f4a435ff1c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericStart"",
                    ""type"": ""Button"",
                    ""id"": ""65192994-a2d9-4b08-886e-e2fac31e9be0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericDPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""f236ed2f-6ecb-4197-98a3-1a30dd9487c4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericDPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""a2519091-49da-4264-87f8-5c3aa21d0f8a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericDPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""f225dac5-988f-4d3b-a459-151dee21cc79"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenericDPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""50a99789-577f-4fdc-93d1-e8415e48a1f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""35cc5cee-232d-48f3-8d91-0df1e373c1da"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8916791a-c1fe-4156-905f-023f6b6420d6"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd65ff12-8e6b-4a88-b8b2-a6a2b7236993"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f35df039-4b88-4ef1-a7ba-339732ede61b"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25344e41-45c4-4ffd-b239-864af61e9d45"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericLB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55148822-01c4-4b29-9783-b419bc6a5ad0"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericLT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""176111ba-5c77-488e-8286-9aabb4af4376"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericRB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a2a52d9-b73e-4902-b238-258608d2e8b9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericRT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26e81174-ae10-4337-aba4-db01a56fd1fc"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericL3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""535d313a-4dee-4f0e-a6ca-57a38e53ad3d"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericR3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12c480d7-fa47-40f8-a628-d9b5821e6bef"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f584e47-b45f-4f36-9851-527f233c5c53"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""209742b7-2754-45aa-900a-602c26f1a08b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericDPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ad1120a-a11d-49d5-b288-ba60914981d8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericDPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2c8a5b5-81d4-4494-9477-41f7389c8f5c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericDPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf8c981d-5836-45b8-bd41-530314fc7ea1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenericDPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Playstation"",
            ""id"": ""58ce8707-b0d1-4fb2-934b-eff464157b4f"",
            ""actions"": [
                {
                    ""name"": ""PlaystationCross"",
                    ""type"": ""Button"",
                    ""id"": ""5b8c9ddb-4bbc-47d5-a937-c09408f0daba"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationSquare"",
                    ""type"": ""Button"",
                    ""id"": ""b4c80732-96e4-4be8-ae2d-b160a0e4c4de"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationTriangle"",
                    ""type"": ""Button"",
                    ""id"": ""e1f8fdc4-c65c-41aa-9739-73e911153da2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationCircle"",
                    ""type"": ""Button"",
                    ""id"": ""0f926cc0-ff65-48e1-84c0-426bf70bef0f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationL1"",
                    ""type"": ""Button"",
                    ""id"": ""f37d83bc-de90-4ed4-becc-66bd61f7c137"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationL2"",
                    ""type"": ""Button"",
                    ""id"": ""3c4bc38d-e3b6-425e-8323-14aa781a05b0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationR1"",
                    ""type"": ""Button"",
                    ""id"": ""342b6109-5741-4e4a-b9be-c3d70e367e63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationR2"",
                    ""type"": ""Button"",
                    ""id"": ""55bb26b2-f77a-4710-9178-c3d961e33e73"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationSelect"",
                    ""type"": ""Button"",
                    ""id"": ""90bc0a9e-f768-43a0-908c-6249fd547d72"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationStart"",
                    ""type"": ""Button"",
                    ""id"": ""c54d11b8-c760-4cb4-ad76-dfee3903ab70"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationDPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""dba685ad-c058-4977-a5fd-b24c9338c78c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationDPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c4a35d2a-7ab4-4ad8-a82d-82896ab6ef3a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationDPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""e7f91a6d-a9ec-42c8-975b-2ffc9f302aa5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationDPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""1e5bafc7-0bfa-427f-a0ab-7882cfe4d6b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationL3"",
                    ""type"": ""Button"",
                    ""id"": ""603d910b-0fcd-402c-8913-1a98d68da0d7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaystationR3"",
                    ""type"": ""Button"",
                    ""id"": ""e77c834b-87b2-40c6-b57d-d8a1d7660a85"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8650c62-2121-4bb6-bf0c-1965def4829c"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f4ef1c6-255c-46f5-a8fb-e475449e2153"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationSquare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bf3626d-fa68-4fb5-8944-82de6447ec43"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationTriangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57918a6e-d49d-45e6-94de-17f2c76af84b"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4766ab67-cd1c-4f10-aa7e-8614ca878924"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationL1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f3735d0-0118-493a-b34f-8270a9c8d44f"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationL2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""232066f1-f354-4c2a-842b-eadb75609ff4"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationR1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3637924-f71c-4a65-9769-892476119faa"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationR2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c67b0d9-4b08-4812-9913-718abc3de76a"",
                    ""path"": ""<DualShockGamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38b80dfc-712a-402a-a78d-7b385acccd34"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b48a242-282a-4aa1-bbbf-06cebd4890a1"",
                    ""path"": ""<DualShockGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationDPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d76fddfa-3668-4861-8119-5d77a3301c06"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationDPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1417fc72-509a-45e0-a7b1-d72db5be4d2c"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationDPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c26b74be-b5db-4d87-94ce-e2af3e001287"",
                    ""path"": ""<DualShockGamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationDPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf6c17b6-2a28-40b9-900f-608cfe54a525"",
                    ""path"": ""<DualShockGamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationL3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6613d9cd-4215-4ddf-94ef-854669196e09"",
                    ""path"": ""<DualShockGamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaystationR3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KBM"",
            ""id"": ""27dd13f4-5bad-442f-bc6b-ae6c3400ab14"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""3003ed75-f083-42e8-a1ad-9881c59c5640"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f0b5dcef-1740-4f65-b912-28cc2dd14ef8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Generic
        m_Generic = asset.FindActionMap("Generic", throwIfNotFound: true);
        m_Generic_GenericA = m_Generic.FindAction("GenericA", throwIfNotFound: true);
        m_Generic_GenericB = m_Generic.FindAction("GenericB", throwIfNotFound: true);
        m_Generic_GenericY = m_Generic.FindAction("GenericY", throwIfNotFound: true);
        m_Generic_GenericX = m_Generic.FindAction("GenericX", throwIfNotFound: true);
        m_Generic_GenericLB = m_Generic.FindAction("GenericLB", throwIfNotFound: true);
        m_Generic_GenericLT = m_Generic.FindAction("GenericLT", throwIfNotFound: true);
        m_Generic_GenericRB = m_Generic.FindAction("GenericRB", throwIfNotFound: true);
        m_Generic_GenericRT = m_Generic.FindAction("GenericRT", throwIfNotFound: true);
        m_Generic_GenericL3 = m_Generic.FindAction("GenericL3", throwIfNotFound: true);
        m_Generic_GenericR3 = m_Generic.FindAction("GenericR3", throwIfNotFound: true);
        m_Generic_GenericSelect = m_Generic.FindAction("GenericSelect", throwIfNotFound: true);
        m_Generic_GenericStart = m_Generic.FindAction("GenericStart", throwIfNotFound: true);
        m_Generic_GenericDPadUp = m_Generic.FindAction("GenericDPadUp", throwIfNotFound: true);
        m_Generic_GenericDPadLeft = m_Generic.FindAction("GenericDPadLeft", throwIfNotFound: true);
        m_Generic_GenericDPadRight = m_Generic.FindAction("GenericDPadRight", throwIfNotFound: true);
        m_Generic_GenericDPadDown = m_Generic.FindAction("GenericDPadDown", throwIfNotFound: true);
        // Playstation
        m_Playstation = asset.FindActionMap("Playstation", throwIfNotFound: true);
        m_Playstation_PlaystationCross = m_Playstation.FindAction("PlaystationCross", throwIfNotFound: true);
        m_Playstation_PlaystationSquare = m_Playstation.FindAction("PlaystationSquare", throwIfNotFound: true);
        m_Playstation_PlaystationTriangle = m_Playstation.FindAction("PlaystationTriangle", throwIfNotFound: true);
        m_Playstation_PlaystationCircle = m_Playstation.FindAction("PlaystationCircle", throwIfNotFound: true);
        m_Playstation_PlaystationL1 = m_Playstation.FindAction("PlaystationL1", throwIfNotFound: true);
        m_Playstation_PlaystationL2 = m_Playstation.FindAction("PlaystationL2", throwIfNotFound: true);
        m_Playstation_PlaystationR1 = m_Playstation.FindAction("PlaystationR1", throwIfNotFound: true);
        m_Playstation_PlaystationR2 = m_Playstation.FindAction("PlaystationR2", throwIfNotFound: true);
        m_Playstation_PlaystationSelect = m_Playstation.FindAction("PlaystationSelect", throwIfNotFound: true);
        m_Playstation_PlaystationStart = m_Playstation.FindAction("PlaystationStart", throwIfNotFound: true);
        m_Playstation_PlaystationDPadUp = m_Playstation.FindAction("PlaystationDPadUp", throwIfNotFound: true);
        m_Playstation_PlaystationDPadLeft = m_Playstation.FindAction("PlaystationDPadLeft", throwIfNotFound: true);
        m_Playstation_PlaystationDPadRight = m_Playstation.FindAction("PlaystationDPadRight", throwIfNotFound: true);
        m_Playstation_PlaystationDPadDown = m_Playstation.FindAction("PlaystationDPadDown", throwIfNotFound: true);
        m_Playstation_PlaystationL3 = m_Playstation.FindAction("PlaystationL3", throwIfNotFound: true);
        m_Playstation_PlaystationR3 = m_Playstation.FindAction("PlaystationR3", throwIfNotFound: true);
        // KBM
        m_KBM = asset.FindActionMap("KBM", throwIfNotFound: true);
        m_KBM_Newaction = m_KBM.FindAction("New action", throwIfNotFound: true);
    }

    ~@MainInputActions()
    {
        UnityEngine.Debug.Assert(!m_Generic.enabled, "This will cause a leak and performance issues, MainInputActions.Generic.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Playstation.enabled, "This will cause a leak and performance issues, MainInputActions.Playstation.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_KBM.enabled, "This will cause a leak and performance issues, MainInputActions.KBM.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Generic
    private readonly InputActionMap m_Generic;
    private List<IGenericActions> m_GenericActionsCallbackInterfaces = new List<IGenericActions>();
    private readonly InputAction m_Generic_GenericA;
    private readonly InputAction m_Generic_GenericB;
    private readonly InputAction m_Generic_GenericY;
    private readonly InputAction m_Generic_GenericX;
    private readonly InputAction m_Generic_GenericLB;
    private readonly InputAction m_Generic_GenericLT;
    private readonly InputAction m_Generic_GenericRB;
    private readonly InputAction m_Generic_GenericRT;
    private readonly InputAction m_Generic_GenericL3;
    private readonly InputAction m_Generic_GenericR3;
    private readonly InputAction m_Generic_GenericSelect;
    private readonly InputAction m_Generic_GenericStart;
    private readonly InputAction m_Generic_GenericDPadUp;
    private readonly InputAction m_Generic_GenericDPadLeft;
    private readonly InputAction m_Generic_GenericDPadRight;
    private readonly InputAction m_Generic_GenericDPadDown;
    public struct GenericActions
    {
        private @MainInputActions m_Wrapper;
        public GenericActions(@MainInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @GenericA => m_Wrapper.m_Generic_GenericA;
        public InputAction @GenericB => m_Wrapper.m_Generic_GenericB;
        public InputAction @GenericY => m_Wrapper.m_Generic_GenericY;
        public InputAction @GenericX => m_Wrapper.m_Generic_GenericX;
        public InputAction @GenericLB => m_Wrapper.m_Generic_GenericLB;
        public InputAction @GenericLT => m_Wrapper.m_Generic_GenericLT;
        public InputAction @GenericRB => m_Wrapper.m_Generic_GenericRB;
        public InputAction @GenericRT => m_Wrapper.m_Generic_GenericRT;
        public InputAction @GenericL3 => m_Wrapper.m_Generic_GenericL3;
        public InputAction @GenericR3 => m_Wrapper.m_Generic_GenericR3;
        public InputAction @GenericSelect => m_Wrapper.m_Generic_GenericSelect;
        public InputAction @GenericStart => m_Wrapper.m_Generic_GenericStart;
        public InputAction @GenericDPadUp => m_Wrapper.m_Generic_GenericDPadUp;
        public InputAction @GenericDPadLeft => m_Wrapper.m_Generic_GenericDPadLeft;
        public InputAction @GenericDPadRight => m_Wrapper.m_Generic_GenericDPadRight;
        public InputAction @GenericDPadDown => m_Wrapper.m_Generic_GenericDPadDown;
        public InputActionMap Get() { return m_Wrapper.m_Generic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GenericActions set) { return set.Get(); }
        public void AddCallbacks(IGenericActions instance)
        {
            if (instance == null || m_Wrapper.m_GenericActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GenericActionsCallbackInterfaces.Add(instance);
            @GenericA.started += instance.OnGenericA;
            @GenericA.performed += instance.OnGenericA;
            @GenericA.canceled += instance.OnGenericA;
            @GenericB.started += instance.OnGenericB;
            @GenericB.performed += instance.OnGenericB;
            @GenericB.canceled += instance.OnGenericB;
            @GenericY.started += instance.OnGenericY;
            @GenericY.performed += instance.OnGenericY;
            @GenericY.canceled += instance.OnGenericY;
            @GenericX.started += instance.OnGenericX;
            @GenericX.performed += instance.OnGenericX;
            @GenericX.canceled += instance.OnGenericX;
            @GenericLB.started += instance.OnGenericLB;
            @GenericLB.performed += instance.OnGenericLB;
            @GenericLB.canceled += instance.OnGenericLB;
            @GenericLT.started += instance.OnGenericLT;
            @GenericLT.performed += instance.OnGenericLT;
            @GenericLT.canceled += instance.OnGenericLT;
            @GenericRB.started += instance.OnGenericRB;
            @GenericRB.performed += instance.OnGenericRB;
            @GenericRB.canceled += instance.OnGenericRB;
            @GenericRT.started += instance.OnGenericRT;
            @GenericRT.performed += instance.OnGenericRT;
            @GenericRT.canceled += instance.OnGenericRT;
            @GenericL3.started += instance.OnGenericL3;
            @GenericL3.performed += instance.OnGenericL3;
            @GenericL3.canceled += instance.OnGenericL3;
            @GenericR3.started += instance.OnGenericR3;
            @GenericR3.performed += instance.OnGenericR3;
            @GenericR3.canceled += instance.OnGenericR3;
            @GenericSelect.started += instance.OnGenericSelect;
            @GenericSelect.performed += instance.OnGenericSelect;
            @GenericSelect.canceled += instance.OnGenericSelect;
            @GenericStart.started += instance.OnGenericStart;
            @GenericStart.performed += instance.OnGenericStart;
            @GenericStart.canceled += instance.OnGenericStart;
            @GenericDPadUp.started += instance.OnGenericDPadUp;
            @GenericDPadUp.performed += instance.OnGenericDPadUp;
            @GenericDPadUp.canceled += instance.OnGenericDPadUp;
            @GenericDPadLeft.started += instance.OnGenericDPadLeft;
            @GenericDPadLeft.performed += instance.OnGenericDPadLeft;
            @GenericDPadLeft.canceled += instance.OnGenericDPadLeft;
            @GenericDPadRight.started += instance.OnGenericDPadRight;
            @GenericDPadRight.performed += instance.OnGenericDPadRight;
            @GenericDPadRight.canceled += instance.OnGenericDPadRight;
            @GenericDPadDown.started += instance.OnGenericDPadDown;
            @GenericDPadDown.performed += instance.OnGenericDPadDown;
            @GenericDPadDown.canceled += instance.OnGenericDPadDown;
        }

        private void UnregisterCallbacks(IGenericActions instance)
        {
            @GenericA.started -= instance.OnGenericA;
            @GenericA.performed -= instance.OnGenericA;
            @GenericA.canceled -= instance.OnGenericA;
            @GenericB.started -= instance.OnGenericB;
            @GenericB.performed -= instance.OnGenericB;
            @GenericB.canceled -= instance.OnGenericB;
            @GenericY.started -= instance.OnGenericY;
            @GenericY.performed -= instance.OnGenericY;
            @GenericY.canceled -= instance.OnGenericY;
            @GenericX.started -= instance.OnGenericX;
            @GenericX.performed -= instance.OnGenericX;
            @GenericX.canceled -= instance.OnGenericX;
            @GenericLB.started -= instance.OnGenericLB;
            @GenericLB.performed -= instance.OnGenericLB;
            @GenericLB.canceled -= instance.OnGenericLB;
            @GenericLT.started -= instance.OnGenericLT;
            @GenericLT.performed -= instance.OnGenericLT;
            @GenericLT.canceled -= instance.OnGenericLT;
            @GenericRB.started -= instance.OnGenericRB;
            @GenericRB.performed -= instance.OnGenericRB;
            @GenericRB.canceled -= instance.OnGenericRB;
            @GenericRT.started -= instance.OnGenericRT;
            @GenericRT.performed -= instance.OnGenericRT;
            @GenericRT.canceled -= instance.OnGenericRT;
            @GenericL3.started -= instance.OnGenericL3;
            @GenericL3.performed -= instance.OnGenericL3;
            @GenericL3.canceled -= instance.OnGenericL3;
            @GenericR3.started -= instance.OnGenericR3;
            @GenericR3.performed -= instance.OnGenericR3;
            @GenericR3.canceled -= instance.OnGenericR3;
            @GenericSelect.started -= instance.OnGenericSelect;
            @GenericSelect.performed -= instance.OnGenericSelect;
            @GenericSelect.canceled -= instance.OnGenericSelect;
            @GenericStart.started -= instance.OnGenericStart;
            @GenericStart.performed -= instance.OnGenericStart;
            @GenericStart.canceled -= instance.OnGenericStart;
            @GenericDPadUp.started -= instance.OnGenericDPadUp;
            @GenericDPadUp.performed -= instance.OnGenericDPadUp;
            @GenericDPadUp.canceled -= instance.OnGenericDPadUp;
            @GenericDPadLeft.started -= instance.OnGenericDPadLeft;
            @GenericDPadLeft.performed -= instance.OnGenericDPadLeft;
            @GenericDPadLeft.canceled -= instance.OnGenericDPadLeft;
            @GenericDPadRight.started -= instance.OnGenericDPadRight;
            @GenericDPadRight.performed -= instance.OnGenericDPadRight;
            @GenericDPadRight.canceled -= instance.OnGenericDPadRight;
            @GenericDPadDown.started -= instance.OnGenericDPadDown;
            @GenericDPadDown.performed -= instance.OnGenericDPadDown;
            @GenericDPadDown.canceled -= instance.OnGenericDPadDown;
        }

        public void RemoveCallbacks(IGenericActions instance)
        {
            if (m_Wrapper.m_GenericActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGenericActions instance)
        {
            foreach (var item in m_Wrapper.m_GenericActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GenericActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GenericActions @Generic => new GenericActions(this);

    // Playstation
    private readonly InputActionMap m_Playstation;
    private List<IPlaystationActions> m_PlaystationActionsCallbackInterfaces = new List<IPlaystationActions>();
    private readonly InputAction m_Playstation_PlaystationCross;
    private readonly InputAction m_Playstation_PlaystationSquare;
    private readonly InputAction m_Playstation_PlaystationTriangle;
    private readonly InputAction m_Playstation_PlaystationCircle;
    private readonly InputAction m_Playstation_PlaystationL1;
    private readonly InputAction m_Playstation_PlaystationL2;
    private readonly InputAction m_Playstation_PlaystationR1;
    private readonly InputAction m_Playstation_PlaystationR2;
    private readonly InputAction m_Playstation_PlaystationSelect;
    private readonly InputAction m_Playstation_PlaystationStart;
    private readonly InputAction m_Playstation_PlaystationDPadUp;
    private readonly InputAction m_Playstation_PlaystationDPadLeft;
    private readonly InputAction m_Playstation_PlaystationDPadRight;
    private readonly InputAction m_Playstation_PlaystationDPadDown;
    private readonly InputAction m_Playstation_PlaystationL3;
    private readonly InputAction m_Playstation_PlaystationR3;
    public struct PlaystationActions
    {
        private @MainInputActions m_Wrapper;
        public PlaystationActions(@MainInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlaystationCross => m_Wrapper.m_Playstation_PlaystationCross;
        public InputAction @PlaystationSquare => m_Wrapper.m_Playstation_PlaystationSquare;
        public InputAction @PlaystationTriangle => m_Wrapper.m_Playstation_PlaystationTriangle;
        public InputAction @PlaystationCircle => m_Wrapper.m_Playstation_PlaystationCircle;
        public InputAction @PlaystationL1 => m_Wrapper.m_Playstation_PlaystationL1;
        public InputAction @PlaystationL2 => m_Wrapper.m_Playstation_PlaystationL2;
        public InputAction @PlaystationR1 => m_Wrapper.m_Playstation_PlaystationR1;
        public InputAction @PlaystationR2 => m_Wrapper.m_Playstation_PlaystationR2;
        public InputAction @PlaystationSelect => m_Wrapper.m_Playstation_PlaystationSelect;
        public InputAction @PlaystationStart => m_Wrapper.m_Playstation_PlaystationStart;
        public InputAction @PlaystationDPadUp => m_Wrapper.m_Playstation_PlaystationDPadUp;
        public InputAction @PlaystationDPadLeft => m_Wrapper.m_Playstation_PlaystationDPadLeft;
        public InputAction @PlaystationDPadRight => m_Wrapper.m_Playstation_PlaystationDPadRight;
        public InputAction @PlaystationDPadDown => m_Wrapper.m_Playstation_PlaystationDPadDown;
        public InputAction @PlaystationL3 => m_Wrapper.m_Playstation_PlaystationL3;
        public InputAction @PlaystationR3 => m_Wrapper.m_Playstation_PlaystationR3;
        public InputActionMap Get() { return m_Wrapper.m_Playstation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlaystationActions set) { return set.Get(); }
        public void AddCallbacks(IPlaystationActions instance)
        {
            if (instance == null || m_Wrapper.m_PlaystationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlaystationActionsCallbackInterfaces.Add(instance);
            @PlaystationCross.started += instance.OnPlaystationCross;
            @PlaystationCross.performed += instance.OnPlaystationCross;
            @PlaystationCross.canceled += instance.OnPlaystationCross;
            @PlaystationSquare.started += instance.OnPlaystationSquare;
            @PlaystationSquare.performed += instance.OnPlaystationSquare;
            @PlaystationSquare.canceled += instance.OnPlaystationSquare;
            @PlaystationTriangle.started += instance.OnPlaystationTriangle;
            @PlaystationTriangle.performed += instance.OnPlaystationTriangle;
            @PlaystationTriangle.canceled += instance.OnPlaystationTriangle;
            @PlaystationCircle.started += instance.OnPlaystationCircle;
            @PlaystationCircle.performed += instance.OnPlaystationCircle;
            @PlaystationCircle.canceled += instance.OnPlaystationCircle;
            @PlaystationL1.started += instance.OnPlaystationL1;
            @PlaystationL1.performed += instance.OnPlaystationL1;
            @PlaystationL1.canceled += instance.OnPlaystationL1;
            @PlaystationL2.started += instance.OnPlaystationL2;
            @PlaystationL2.performed += instance.OnPlaystationL2;
            @PlaystationL2.canceled += instance.OnPlaystationL2;
            @PlaystationR1.started += instance.OnPlaystationR1;
            @PlaystationR1.performed += instance.OnPlaystationR1;
            @PlaystationR1.canceled += instance.OnPlaystationR1;
            @PlaystationR2.started += instance.OnPlaystationR2;
            @PlaystationR2.performed += instance.OnPlaystationR2;
            @PlaystationR2.canceled += instance.OnPlaystationR2;
            @PlaystationSelect.started += instance.OnPlaystationSelect;
            @PlaystationSelect.performed += instance.OnPlaystationSelect;
            @PlaystationSelect.canceled += instance.OnPlaystationSelect;
            @PlaystationStart.started += instance.OnPlaystationStart;
            @PlaystationStart.performed += instance.OnPlaystationStart;
            @PlaystationStart.canceled += instance.OnPlaystationStart;
            @PlaystationDPadUp.started += instance.OnPlaystationDPadUp;
            @PlaystationDPadUp.performed += instance.OnPlaystationDPadUp;
            @PlaystationDPadUp.canceled += instance.OnPlaystationDPadUp;
            @PlaystationDPadLeft.started += instance.OnPlaystationDPadLeft;
            @PlaystationDPadLeft.performed += instance.OnPlaystationDPadLeft;
            @PlaystationDPadLeft.canceled += instance.OnPlaystationDPadLeft;
            @PlaystationDPadRight.started += instance.OnPlaystationDPadRight;
            @PlaystationDPadRight.performed += instance.OnPlaystationDPadRight;
            @PlaystationDPadRight.canceled += instance.OnPlaystationDPadRight;
            @PlaystationDPadDown.started += instance.OnPlaystationDPadDown;
            @PlaystationDPadDown.performed += instance.OnPlaystationDPadDown;
            @PlaystationDPadDown.canceled += instance.OnPlaystationDPadDown;
            @PlaystationL3.started += instance.OnPlaystationL3;
            @PlaystationL3.performed += instance.OnPlaystationL3;
            @PlaystationL3.canceled += instance.OnPlaystationL3;
            @PlaystationR3.started += instance.OnPlaystationR3;
            @PlaystationR3.performed += instance.OnPlaystationR3;
            @PlaystationR3.canceled += instance.OnPlaystationR3;
        }

        private void UnregisterCallbacks(IPlaystationActions instance)
        {
            @PlaystationCross.started -= instance.OnPlaystationCross;
            @PlaystationCross.performed -= instance.OnPlaystationCross;
            @PlaystationCross.canceled -= instance.OnPlaystationCross;
            @PlaystationSquare.started -= instance.OnPlaystationSquare;
            @PlaystationSquare.performed -= instance.OnPlaystationSquare;
            @PlaystationSquare.canceled -= instance.OnPlaystationSquare;
            @PlaystationTriangle.started -= instance.OnPlaystationTriangle;
            @PlaystationTriangle.performed -= instance.OnPlaystationTriangle;
            @PlaystationTriangle.canceled -= instance.OnPlaystationTriangle;
            @PlaystationCircle.started -= instance.OnPlaystationCircle;
            @PlaystationCircle.performed -= instance.OnPlaystationCircle;
            @PlaystationCircle.canceled -= instance.OnPlaystationCircle;
            @PlaystationL1.started -= instance.OnPlaystationL1;
            @PlaystationL1.performed -= instance.OnPlaystationL1;
            @PlaystationL1.canceled -= instance.OnPlaystationL1;
            @PlaystationL2.started -= instance.OnPlaystationL2;
            @PlaystationL2.performed -= instance.OnPlaystationL2;
            @PlaystationL2.canceled -= instance.OnPlaystationL2;
            @PlaystationR1.started -= instance.OnPlaystationR1;
            @PlaystationR1.performed -= instance.OnPlaystationR1;
            @PlaystationR1.canceled -= instance.OnPlaystationR1;
            @PlaystationR2.started -= instance.OnPlaystationR2;
            @PlaystationR2.performed -= instance.OnPlaystationR2;
            @PlaystationR2.canceled -= instance.OnPlaystationR2;
            @PlaystationSelect.started -= instance.OnPlaystationSelect;
            @PlaystationSelect.performed -= instance.OnPlaystationSelect;
            @PlaystationSelect.canceled -= instance.OnPlaystationSelect;
            @PlaystationStart.started -= instance.OnPlaystationStart;
            @PlaystationStart.performed -= instance.OnPlaystationStart;
            @PlaystationStart.canceled -= instance.OnPlaystationStart;
            @PlaystationDPadUp.started -= instance.OnPlaystationDPadUp;
            @PlaystationDPadUp.performed -= instance.OnPlaystationDPadUp;
            @PlaystationDPadUp.canceled -= instance.OnPlaystationDPadUp;
            @PlaystationDPadLeft.started -= instance.OnPlaystationDPadLeft;
            @PlaystationDPadLeft.performed -= instance.OnPlaystationDPadLeft;
            @PlaystationDPadLeft.canceled -= instance.OnPlaystationDPadLeft;
            @PlaystationDPadRight.started -= instance.OnPlaystationDPadRight;
            @PlaystationDPadRight.performed -= instance.OnPlaystationDPadRight;
            @PlaystationDPadRight.canceled -= instance.OnPlaystationDPadRight;
            @PlaystationDPadDown.started -= instance.OnPlaystationDPadDown;
            @PlaystationDPadDown.performed -= instance.OnPlaystationDPadDown;
            @PlaystationDPadDown.canceled -= instance.OnPlaystationDPadDown;
            @PlaystationL3.started -= instance.OnPlaystationL3;
            @PlaystationL3.performed -= instance.OnPlaystationL3;
            @PlaystationL3.canceled -= instance.OnPlaystationL3;
            @PlaystationR3.started -= instance.OnPlaystationR3;
            @PlaystationR3.performed -= instance.OnPlaystationR3;
            @PlaystationR3.canceled -= instance.OnPlaystationR3;
        }

        public void RemoveCallbacks(IPlaystationActions instance)
        {
            if (m_Wrapper.m_PlaystationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlaystationActions instance)
        {
            foreach (var item in m_Wrapper.m_PlaystationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlaystationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlaystationActions @Playstation => new PlaystationActions(this);

    // KBM
    private readonly InputActionMap m_KBM;
    private List<IKBMActions> m_KBMActionsCallbackInterfaces = new List<IKBMActions>();
    private readonly InputAction m_KBM_Newaction;
    public struct KBMActions
    {
        private @MainInputActions m_Wrapper;
        public KBMActions(@MainInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_KBM_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_KBM; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KBMActions set) { return set.Get(); }
        public void AddCallbacks(IKBMActions instance)
        {
            if (instance == null || m_Wrapper.m_KBMActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KBMActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IKBMActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IKBMActions instance)
        {
            if (m_Wrapper.m_KBMActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKBMActions instance)
        {
            foreach (var item in m_Wrapper.m_KBMActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KBMActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KBMActions @KBM => new KBMActions(this);
    public interface IGenericActions
    {
        void OnGenericA(InputAction.CallbackContext context);
        void OnGenericB(InputAction.CallbackContext context);
        void OnGenericY(InputAction.CallbackContext context);
        void OnGenericX(InputAction.CallbackContext context);
        void OnGenericLB(InputAction.CallbackContext context);
        void OnGenericLT(InputAction.CallbackContext context);
        void OnGenericRB(InputAction.CallbackContext context);
        void OnGenericRT(InputAction.CallbackContext context);
        void OnGenericL3(InputAction.CallbackContext context);
        void OnGenericR3(InputAction.CallbackContext context);
        void OnGenericSelect(InputAction.CallbackContext context);
        void OnGenericStart(InputAction.CallbackContext context);
        void OnGenericDPadUp(InputAction.CallbackContext context);
        void OnGenericDPadLeft(InputAction.CallbackContext context);
        void OnGenericDPadRight(InputAction.CallbackContext context);
        void OnGenericDPadDown(InputAction.CallbackContext context);
    }
    public interface IPlaystationActions
    {
        void OnPlaystationCross(InputAction.CallbackContext context);
        void OnPlaystationSquare(InputAction.CallbackContext context);
        void OnPlaystationTriangle(InputAction.CallbackContext context);
        void OnPlaystationCircle(InputAction.CallbackContext context);
        void OnPlaystationL1(InputAction.CallbackContext context);
        void OnPlaystationL2(InputAction.CallbackContext context);
        void OnPlaystationR1(InputAction.CallbackContext context);
        void OnPlaystationR2(InputAction.CallbackContext context);
        void OnPlaystationSelect(InputAction.CallbackContext context);
        void OnPlaystationStart(InputAction.CallbackContext context);
        void OnPlaystationDPadUp(InputAction.CallbackContext context);
        void OnPlaystationDPadLeft(InputAction.CallbackContext context);
        void OnPlaystationDPadRight(InputAction.CallbackContext context);
        void OnPlaystationDPadDown(InputAction.CallbackContext context);
        void OnPlaystationL3(InputAction.CallbackContext context);
        void OnPlaystationR3(InputAction.CallbackContext context);
    }
    public interface IKBMActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
